apiVersion: v1
kind: ConfigMap
metadata:
  name: moneypenny-quips
  namespace: moneypenny
data:
  quips.txt: |
    Flattery will get you nowhere... but don't stop trying.
    %
    You never take me to dinner looking like this, James. You never take me to dinner, period.
    %
    M: (on intercom) Miss Moneypenny, give 007 the password we've agreed
    with Japanese SIS.
    Moneypenny: Yes, Sir. We tried to think of something that you wouldn't
    forget.
    Bond: Yes?
    Moneypenny: I... love... you. Repeat it please, to make sure you get it.
    Bond: Don't worry, I get it. Sayonara. 
    %
    My problem is, James, you never do anything with me.
    %
    I didn't know you were a music lover. Any time you want to come over and hear my Barry Manilow collection...
    %
    Someday you'll have to make good on your innuendos.
    %
    You always were a cunning linguist, James.
    %
    Bond: (about getting shot) In your defense, a moving target is harder to hit.
    Moneypenny: Then you'd better keep moving.
    %
    Moneypenny: Cut-throat razor. How very traditional.
    Bond: Well, I like to do some things the old-fashioned way.
    Moneypenny: Sometimes the old ways are best.
