apiVersion: apps/v1
kind: Deployment
metadata:
  name: moneypenny
  labels:
    name: moneypenny
spec:
  replicas: 1
  selector:
    matchLabels:
      name: moneypenny
  template:
    metadata:
      labels:
        name: moneypenny
    spec:
      containers:
        - name: moneypenny
          imagePullPolicy: "Always"
          image: "lsstsqre/moneypenny:latest"
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: moneypenny
          securityContext:
            capabilities:
              drop:
                - all
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
          - name: m-config
            mountPath: /opt/lsst/software/moneypenny/config/M
            readOnly: true
          - name: quips
            mountPath: /opt/lsst/software/moneypenny/config/quips
            readOnly: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      serviceAccountName: moneypenny
      volumes:
      - name: m-config
        configMap:
          name: moneypenny-m-config
      - name: quips
        configMap:
          name: moneypenny-quips

