kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: moneypenny
rules:
- apiGroups: [""]
  resources: [ "pods" ]
  verbs: ["get", "create",  "delete"]  
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create",  "delete"]
