kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: moneypenny
subjects:
- kind: ServiceAccount
  name: moneypenny
roleRef:
  kind: Role
  name: moneypenny
  apiGroup: rbac.authorization.k8s.io
