apiVersion: v1
kind: Service
metadata:
  name: moneypenny
  labels:
    name: moneypenny
spec:
  type: NodePort
  ports:
  - name: moneypenny-http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    name: moneypenny
