host: "data-dev.lsst.cloud"

image:
  tag: dev
  pullPolicy: Never

ingress:
  enabled: true
  hosts:
    - host: data-dev.lsst.cloud
      paths: ["/moneypenny"]

vault_secrets:
  enabled: true
  path: "secret/k8s_operator/data-dev.lsst.cloud/moneypenny"
